<?php
/**
 * Language labels for database tables/fields belonging to extension "vm19_docs_base"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"tx_vm19docsbase_topics" => "topics",	
		"tx_vm19docsbase_topics.title" => "topics title",	
		"tx_vm19docsbase_topics.comment" => "comment",	
		"tx_vm19docsbase_support" => "support",	
		"tx_vm19docsbase_support.title" => "title",	
		"tx_vm19docsbase_support.comment" => "comment",	
		"tx_vm19docsbase_nature" => "nature",	
		"tx_vm19docsbase_nature.title" => "title",	
		"tx_vm19docsbase_nature.comment" => "comment",	
		"tx_vm19docsbase_lang" => "lang",	
		"tx_vm19docsbase_lang.langcode" => "lang code",	
		"tx_vm19docsbase_lang.title" => "title",	
		"tx_vm19docsbase_docs" => "documents",	
		"tx_vm19docsbase_docs.internal_code" => "internal code",	
		"tx_vm19docsbase_docs.title" => "title",	
		"tx_vm19docsbase_docs.topics" => "topics",	
		"tx_vm19docsbase_docs.int_author" => "author, if internal",	
		"tx_vm19docsbase_docs.ext_author" => "author, if external",	
		"tx_vm19docsbase_docs.support" => "support",	
		"tx_vm19docsbase_docs.nature" => "nature",	
		"tx_vm19docsbase_docs.lang" => "lang",	
		"tx_vm19docsbase_docs.source" => "source",	
		"tx_vm19docsbase_docs.isbn" => "ISBN number",	
		"tx_vm19docsbase_docs.keywords" => "key words",	
		"tx_vm19docsbase_docs.abstract" => "abstract",	
		"tx_vm19docsbase_docs.imagette" => "imagette",	
		"tx_vm19docsbase_docs.workflow_state" => "workflow_state",	
		"tx_vm19docsbase_docs.document" => "document",	
		"tt_content.list_type" => "document",	
	),
	"fr" => Array (
		"tx_vm19docsbase_topics" => "Thèmes",	
		"tx_vm19docsbase_topics.title" => "label du thème",	
		"tx_vm19docsbase_topics.comment" => "commentaire",	
		"tx_vm19docsbase_support" => "support",	
		"tx_vm19docsbase_support.title" => "label du support",	
		"tx_vm19docsbase_support.comment" => "commentaire",	
		"tx_vm19docsbase_nature" => "nature",	
		"tx_vm19docsbase_nature.title" => "label",	
		"tx_vm19docsbase_nature.comment" => "commentaire",	
		"tx_vm19docsbase_lang" => "langue",	
		"tx_vm19docsbase_lang.langcode" => "code langue",	
		"tx_vm19docsbase_docs.source" => "source: MAJUSCULES, ex: HARAS NATIONAUX, FIVAL, FFE",	
		"tx_vm19docsbase_lang.title" => "label",	
		"tx_vm19docsbase_docs" => "documents",	
		"tx_vm19docsbase_docs.internal_code" => "code interne",	
		"tx_vm19docsbase_docs.title" => "titre: MAJUSCULES, OBLIGATOIRE",	
		"tx_vm19docsbase_docs.topics" => "intérêts",	
		"tx_vm19docsbase_docs.int_author" => "Auteur, si interne",	
		"tx_vm19docsbase_docs.ext_author" => "Auteur: si différent de l'utilisateur connecté; Format: GAUTIER S.",	
		"tx_vm19docsbase_docs.support" => "support",	
		"tx_vm19docsbase_docs.nature" => "nature",	
		"tx_vm19docsbase_docs.lang" => "langue",	
		"tx_vm19docsbase_docs.isbn" => "No ISBN ou ISSN",	
		"tx_vm19docsbase_docs.keywords" => "mots clés : MAJUSCULES, Singulier, mini3, maxi 5 séparés par des espaces",	
		"tx_vm19docsbase_docs.abstract" => "résumé",	
		"tx_vm19docsbase_docs.imagette" => "imagette",	
		"tx_vm19docsbase_docs.workflow_state" => "etat workflow",	
		"tx_vm19docsbase_docs.document" => "document",	
		"tt_content.list_type" => "document",	
	),
);
?>